FROM node:18.12.1-alpine AS development

# Declaring env
ENV NODE_ENV development

RUN mkdir -p /usr/src/app

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json /usr/src/app
RUN npm install --force

# Copying all the files in our project
COPY . .

# Start the app
CMD npm start